// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurviewConsortium.Infrastructure.Data;

#nullable disable

namespace PurviewConsortium.Infrastructure.Migrations
{
    [DbContext(typeof(ConsortiumDbContext))]
    [Migration("20260217021740_AddPurviewWorkflowStatus")]
    partial class AddPurviewWorkflowStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessJustification")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DataProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalShareId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurviewWorkflowRunId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurviewWorkflowStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestedDurationDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequestingInstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestingUserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestingUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestingUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StatusChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetFabricWorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetLakehouseName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DataProductId");

                    b.HasIndex("RequestingInstitutionId");

                    b.HasIndex("RequestingUserId", "DataProductId");

                    b.HasIndex("Status", "RequestingInstitutionId");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Documentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Endorsed")
                        .HasColumnType("bit");

                    b.Property<string>("GlossaryTermsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernanceDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedFromPurview")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PurviewLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurviewQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensitivityLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsListed");

                    b.HasIndex("Name");

                    b.HasIndex("InstitutionId", "PurviewQualifiedName")
                        .IsUnique();

                    b.ToTable("DataProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            AssetCount = 0,
                            ClassificationsJson = "[\"PHI\",\"De-identified\"]",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "De-identified patient demographic data including age, gender, and geographic region.",
                            Endorsed = false,
                            GlossaryTermsJson = "[\"Consortium-Shareable\",\"Demographics\"]",
                            InstitutionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsListed = true,
                            ModifiedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Patient Demographics",
                            Owner = "Dr. Jane Smith",
                            OwnerEmail = "jsmith@contoso.edu",
                            PurviewQualifiedName = "contoso://datasets/patient-demographics",
                            SensitivityLabel = "Confidential",
                            SourceSystem = "Azure SQL Database"
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-222222222222"),
                            AssetCount = 0,
                            ClassificationsJson = "[\"Research\",\"Aggregated\"]",
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aggregated clinical trial results and outcomes data from 2020-2025.",
                            Endorsed = false,
                            GlossaryTermsJson = "[\"Consortium-Shareable\",\"Clinical-Trials\"]",
                            InstitutionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsListed = true,
                            ModifiedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clinical Trials Summary",
                            Owner = "Dr. Alex Johnson",
                            OwnerEmail = "ajohnson@fabrikam.org",
                            PurviewQualifiedName = "fabrikam://datasets/clinical-trials",
                            SensitivityLabel = "General",
                            SourceSystem = "Fabric Lakehouse"
                        });
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdminConsentGranted")
                        .HasColumnType("bit");

                    b.Property<string>("ConsortiumDomainIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FabricWorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PurviewAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AdminConsentGranted = true,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FabricWorkspaceId = "contoso-workspace-id",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Contoso University",
                            PrimaryContactEmail = "datasteward@contoso.edu",
                            PurviewAccountName = "contoso-purview",
                            TenantId = "contoso-tenant-id"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AdminConsentGranted = true,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FabricWorkspaceId = "fabrikam-workspace-id",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fabrikam Medical Center",
                            PrimaryContactEmail = "data@fabrikam.org",
                            PurviewAccountName = "fabrikam-purview",
                            TenantId = "fabrikam-tenant-id"
                        });
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.SyncHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductsAdded")
                        .HasColumnType("int");

                    b.Property<int>("ProductsDelisted")
                        .HasColumnType("int");

                    b.Property<int>("ProductsFound")
                        .HasColumnType("int");

                    b.Property<int>("ProductsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "StartTime");

                    b.ToTable("SyncHistories");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "InstitutionId")
                        .IsUnique()
                        .HasFilter("[InstitutionId] IS NOT NULL");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AccessRequest", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.DataProduct", "DataProduct")
                        .WithMany("AccessRequests")
                        .HasForeignKey("DataProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "RequestingInstitution")
                        .WithMany("IncomingRequests")
                        .HasForeignKey("RequestingInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataProduct");

                    b.Navigation("RequestingInstitution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany("DataProducts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.SyncHistory", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany("SyncHistories")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.UserRoleAssignment", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.Navigation("AccessRequests");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.Institution", b =>
                {
                    b.Navigation("DataProducts");

                    b.Navigation("IncomingRequests");

                    b.Navigation("SyncHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
