// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurviewConsortium.Infrastructure.Data;

#nullable disable

namespace PurviewConsortium.Infrastructure.Migrations
{
    [DbContext(typeof(ConsortiumDbContext))]
    [Migration("20260313031641_NewDatabase")]
    partial class NewDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessJustification")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DataProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalShareId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("FabricShortcutCreated")
                        .HasColumnType("bit");

                    b.Property<string>("FabricShortcutName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurviewWorkflowRunId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurviewWorkflowStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestedDurationDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequestingInstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestingTenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestingUserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestingUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestingUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ShareType")
                        .HasColumnType("int");

                    b.Property<string>("SourceFabricWorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceInstitutionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceLakehouseItemId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceTenantId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StatusChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetFabricWorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetLakehouseItemId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DataProductId");

                    b.HasIndex("RequestingInstitutionId");

                    b.HasIndex("RequestingUserId", "DataProductId");

                    b.HasIndex("Status", "RequestingInstitutionId");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AssetType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClassificationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FullyQualifiedName")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ProvisioningState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PurviewAssetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PurviewCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PurviewLastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceWorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("InstitutionId", "PurviewAssetId")
                        .IsUnique();

                    b.ToTable("DataAssets");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataAssetsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataQualityScore")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Documentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Endorsed")
                        .HasColumnType("bit");

                    b.Property<string>("GlossaryTermsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernanceDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedFromPurview")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerContactsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PurviewLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurviewQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensitivityLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceLakehouseItemId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfUseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfUseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseCases")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsListed");

                    b.HasIndex("Name");

                    b.HasIndex("InstitutionId", "PurviewQualifiedName")
                        .IsUnique();

                    b.ToTable("DataProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            AssetCount = 0,
                            ClassificationsJson = "[\"PHI\",\"De-identified\"]",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataAssetsJson = "[{\"Name\":\"patient_demographics_v2\",\"Type\":\"Table\",\"Description\":\"Core demographics table with de-identified records\"},{\"Name\":\"geographic_regions\",\"Type\":\"Table\",\"Description\":\"Region lookup and mapping data\"}]",
                            DataQualityScore = 87,
                            Description = "De-identified patient demographic data including age, gender, and geographic region.",
                            DocumentationUrl = "https://contoso.edu/datasets/patient-demographics/docs",
                            Endorsed = false,
                            GlossaryTermsJson = "[\"Consortium-Shareable\",\"Demographics\"]",
                            InstitutionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsListed = true,
                            ModifiedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Patient Demographics",
                            Owner = "Dr. Jane Smith",
                            OwnerEmail = "jsmith@contoso.edu",
                            PurviewQualifiedName = "contoso://datasets/patient-demographics",
                            SensitivityLabel = "Confidential",
                            SourceSystem = "Azure SQL Database",
                            TermsOfUseUrl = "https://contoso.edu/data-sharing/terms",
                            UpdateFrequency = "Weekly",
                            UseCases = "Population health studies, outcome analysis, and demographic trend research across the consortium."
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-222222222222"),
                            AssetCount = 0,
                            ClassificationsJson = "[\"Research\",\"Aggregated\"]",
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataAssetsJson = "[{\"Name\":\"trials_summary_2020_2025\",\"Type\":\"Table\",\"Description\":\"Aggregated trial results and outcomes\"},{\"Name\":\"trial_metadata\",\"Type\":\"Table\",\"Description\":\"Trial identifiers, phases, and sponsors\"},{\"Name\":\"outcomes_analysis\",\"Type\":\"View\",\"Description\":\"Pre-computed outcome statistics\"}]",
                            DataQualityScore = 92,
                            Description = "Aggregated clinical trial results and outcomes data from 2020-2025.",
                            DocumentationUrl = "https://fabrikam.org/datasets/clinical-trials/documentation",
                            Endorsed = false,
                            GlossaryTermsJson = "[\"Consortium-Shareable\",\"Clinical-Trials\"]",
                            InstitutionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsListed = true,
                            ModifiedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clinical Trials Summary",
                            Owner = "Dr. Alex Johnson",
                            OwnerEmail = "ajohnson@fabrikam.org",
                            PurviewQualifiedName = "fabrikam://datasets/clinical-trials",
                            SensitivityLabel = "General",
                            SourceSystem = "Fabric Lakehouse",
                            TermsOfUseUrl = "https://fabrikam.org/data-governance/terms",
                            UpdateFrequency = "Monthly",
                            UseCases = "Cross-institutional research collaboration, meta-analyses of clinical trials, and regulatory reporting."
                        });
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProductDataAsset", b =>
                {
                    b.Property<Guid>("DataProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DataProductId", "DataAssetId");

                    b.HasIndex("DataAssetId");

                    b.ToTable("DataProductDataAssets");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdminConsentGranted")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoFulfillEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ConsortiumDomainIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PurviewAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AdminConsentGranted = true,
                            AutoFulfillEnabled = false,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Contoso University",
                            PrimaryContactEmail = "datasteward@contoso.edu",
                            PurviewAccountName = "contoso-purview",
                            TenantId = "contoso-tenant-id"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AdminConsentGranted = true,
                            AutoFulfillEnabled = false,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fabrikam Medical Center",
                            PrimaryContactEmail = "data@fabrikam.org",
                            PurviewAccountName = "fabrikam-purview",
                            TenantId = "fabrikam-tenant-id"
                        });
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.SyncHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductsAdded")
                        .HasColumnType("int");

                    b.Property<int>("ProductsDelisted")
                        .HasColumnType("int");

                    b.Property<int>("ProductsFound")
                        .HasColumnType("int");

                    b.Property<int>("ProductsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "StartTime");

                    b.ToTable("SyncHistories");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "InstitutionId")
                        .IsUnique()
                        .HasFilter("[InstitutionId] IS NOT NULL");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.AccessRequest", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.DataProduct", "DataProduct")
                        .WithMany("AccessRequests")
                        .HasForeignKey("DataProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "RequestingInstitution")
                        .WithMany("IncomingRequests")
                        .HasForeignKey("RequestingInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataProduct");

                    b.Navigation("RequestingInstitution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataAsset", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany("DataAssets")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany("DataProducts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProductDataAsset", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.DataAsset", "DataAsset")
                        .WithMany("DataProductDataAssets")
                        .HasForeignKey("DataAssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PurviewConsortium.Core.Entities.DataProduct", "DataProduct")
                        .WithMany("DataProductDataAssets")
                        .HasForeignKey("DataProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAsset");

                    b.Navigation("DataProduct");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.SyncHistory", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany("SyncHistories")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.UserRoleAssignment", b =>
                {
                    b.HasOne("PurviewConsortium.Core.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataAsset", b =>
                {
                    b.Navigation("DataProductDataAssets");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.DataProduct", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("DataProductDataAssets");
                });

            modelBuilder.Entity("PurviewConsortium.Core.Entities.Institution", b =>
                {
                    b.Navigation("DataAssets");

                    b.Navigation("DataProducts");

                    b.Navigation("IncomingRequests");

                    b.Navigation("SyncHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
